name: Cut Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write # Required to create a release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PAT }}
        run: |
          gh release create "${{ github.ref_name }}" --generate-notes
