name: Update Docker Hub Description

on:
  release:
    types: [published]

concurrency:
  # key on workflow name. this is important so that there's no races when
  # multiple releases are created. we want the latest description on Docker Hub
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.IMAGE_REPOSITORY }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
