name: Update Docker Hub Description

on:
  release:
    types: [published]

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.IMAGE_TAG }}
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
